modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszsAccessories/issues"

[[mods]]
    modId="majruszs_accessories"
    version="0.2.0"
    displayName="Majrusz's Accessories"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszsAccessories/1.17.1/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/majruszs-accessories"
    logoFile="logo.png"
    credits="Thanks for all your support!"
    authors="Majrusz"
    description='''Minecraft mod that adds new special accessories that make certain aspects of the game more enjoyable.'''

[[dependencies.majruszs_difficulty]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszs_difficulty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszs_difficulty]]
    modId="majrusz_library"
    mandatory=true
    versionRange="[2.2.0,3.0.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszs_accessories]]
    modId="curios"
    mandatory=false
    versionRange="[1.17.1-5.0.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.majruszs_accessories]]
    modId="majruszs_difficulty"
    mandatory=false
    versionRange="[1.2.0,)"
    ordering="AFTER"
    side="BOTH"