modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszsAccessories/issues"

[[mods]]
    modId="majruszs_accessories"
    version="0.1.0"
    displayName="Majrusz's Accessories"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszsAccessories/1.16.5/update.json"
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
    logoFile="examplemod.png"
    credits="Thanks for all your support!"
    authors="Majrusz"
    description='''Minecraft mod that adds new special accessories that make certain aspects of the game more enjoyable.'''

[[dependencies.majruszs_accessories]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszs_accessories]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszs_accessories]]
    modId="majrusz_library"
    mandatory=true
    versionRange="[2.0.0,3.0.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszs_accessories]]
    modId="curios"
    mandatory=false
    versionRange="[1.16.5-4.0.5.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.majruszs_accessories]]
    modId="majruszs_difficulty"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"