modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszsAccessories/issues"

[[mods]]
    modId="majruszsaccessories"
    version="1.1.0-unfinished"
    displayName="Majrusz's Accessories"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszsAccessories/1.19.X/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/majruszs-accessories"
    logoFile="logo.png"
    credits="Thanks for all your support and downloads!"
    authors="Majrusz"
    description='''Mod that adds new special accessories to make certain aspects of the game more enjoyable.'''

[[dependencies.majruszsaccessories]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="majruszlib"
    mandatory=true
    versionRange="[2.16.0,3.0.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="curios"
    mandatory=false
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="majruszsdifficulty"
    mandatory=false
    versionRange="[1.5.11,)"
    ordering="AFTER"
    side="BOTH"