modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszsAccessories/issues"

[[mods]]
    modId="majruszsaccessories"
    version="0.5.0"
    displayName="Majrusz's Accessories"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszsAccessories/1.19/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/majruszs-accessories"
    logoFile="logo.png"
    credits="Thanks for all your support and downloads!"
    authors="Majrusz"
    description='''Mod that adds new special accessories that make certain aspects of the game more enjoyable.'''

[[dependencies.majruszsaccessories]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="majruszlib"
    mandatory=true
    versionRange="[2.13.0,3.0.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="curios"
    mandatory=false
    versionRange="[1.19-5.1.0.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="majruszsdifficulty"
    mandatory=false
    versionRange="[1.5.7,)"
    ordering="AFTER"
    side="BOTH"